"""Journal table

Revision ID: 000e8d5561ba
Revises: ae0f3ea33a87
Create Date: 2019-03-21 00:30:47.632529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000e8d5561ba'
down_revision = 'ae0f3ea33a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('abbrev', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_abbrev'), 'journal', ['abbrev'], unique=False)
    op.create_index(op.f('ix_journal_name'), 'journal', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_name'), table_name='journal')
    op.drop_index(op.f('ix_journal_abbrev'), table_name='journal')
    op.drop_table('journal')
    # ### end Alembic commands ###
