"""New Ref fields

Revision ID: a19cac1dfd40
Revises: a7cd0f9ed740
Create Date: 2019-03-08 23:37:07.291767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19cac1dfd40'
down_revision = 'a7cd0f9ed740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref', sa.Column('address', sa.String(length=96), nullable=True))
    op.add_column('ref', sa.Column('edition', sa.String(length=16), nullable=True))
    op.add_column('ref', sa.Column('editor', sa.String(length=32), nullable=True))
    op.add_column('ref', sa.Column('entry_type', sa.Integer(), nullable=True))
    op.add_column('ref', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('ref', sa.Column('number', sa.String(length=8), nullable=True))
    op.add_column('ref', sa.Column('publisher', sa.String(length=64), nullable=True))
    op.add_column('ref', sa.Column('series', sa.String(length=32), nullable=True))
    op.add_column('ref', sa.Column('volume', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref', 'volume')
    op.drop_column('ref', 'series')
    op.drop_column('ref', 'publisher')
    op.drop_column('ref', 'number')
    op.drop_column('ref', 'month')
    op.drop_column('ref', 'entry_type')
    op.drop_column('ref', 'editor')
    op.drop_column('ref', 'edition')
    op.drop_column('ref', 'address')
    # ### end Alembic commands ###
