"""Rename authors to author

Revision ID: ae0f3ea33a87
Revises: a19cac1dfd40
Create Date: 2019-03-08 23:41:16.041433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0f3ea33a87'
down_revision = 'a19cac1dfd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref', sa.Column('author', sa.String(length=256), nullable=True))
    with op.batch_alter_table('ref') as batch_op:
        batch_op.drop_column('authors')
    # op.drop_column('ref', 'authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref', sa.Column('authors', sa.VARCHAR(length=256), nullable=True))
    with op.batch_alter_table('ref') as batch_op:
        batch_op.drop_column('author')
    # ### end Alembic commands ###
