"""empty message

Revision ID: f880749be2d7
Revises: 000e8d5561ba
Create Date: 2019-03-23 22:04:47.516248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f880749be2d7'
down_revision = '000e8d5561ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref', sa.Column('bib_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref', 'bib_id')
    # ### end Alembic commands ###
